table_name: dropouts
registry:
  - id
  - created_at
  - updated_at
  - year: { type: varchar, length: 4, allow_null: false }
  - nine_2_twelve: { type: float, allow_null: false }
  - seven_2_twelve: { type: float, allow_null: false }
  - school_id: {type: varchar, length: 10, allow_null: true}
